### ISSUE TITLE
How to get a crosshair? its empty for me. Also how do I change loadout?

### ISSUE THREAD

**Issue by JayBoom** [PapaPeach/PeachHUD#3]
There is no way to have a crosshair that I can see, and if i go into my loadout, I used to have ABCD for like different items on my loadouts, how do i do that now?

**Comment by JayBoom** [comment]
nvm the loadout thing was just hidden but idk about the crosshair

**Comment by PapaPeach** [comment]
You need to go to the customizations folder then edit the Crosshair.res file (preferably with notepad++) and follow the instructions in that. There is also a Crosshair.png file that you can look at to find the crosshair you like.
